In [1]:
import pandas as pd

## Import and prepare the data table

In [2]:
df = pd.read_excel('city_data.xlsx', skiprows=4)

In [3]:
df = df.iloc[:, 2:].set_index('Unnamed: 2')

## Construct an empty grid of the cities

In [4]:
# extract city names
cities = df.index.tolist()

In [5]:
grid = pd.DataFrame(index=cities, columns=cities)

## Fill in grid using the distance formula

In [6]:
df.head()

               Lat  Long
Unnamed: 2
New York      40.7  73.9
Boston        42.3  71.0
Philadelphia  40.0  75.1
Charlotte     35.2  80.8
Atlanta       33.8  84.4

In [7]:
for x in cities:
    for y in cities:
        lat1 = df.loc[x, 'Lat']
        long1 = df.loc[x, 'Long']
        
        lat2 = df.loc[y, 'Lat']
        long2 = df.loc[y, 'Long']
        
        distance = round(69 * ((lat1 - lat2)**2 + (long1 - long2)**2)**0.5)
        
        grid.loc[x, y] = distance

In [8]:
display(grid)

,New York,Boston,Philadelphia,Charlotte,Atlanta,New Orleans,Miami,Dallas,Houston,Chicago,...,Cleveland,Indy,Denver,Minneapolis,Phoenix,Salt Lake City,LA,SF,SD,Seattle
New York,0,229,96,609,867,1328,1116,1671,1663,955,...,541,844,2140,1371,2682,2622,3104,3366,3030,3347
Boston,229,0,324,835,1095,1556,1304,1897,1892,1153,...,740,1056,2345,1550,2900,2824,3319,3574,3248,3547
Philadelphia,96,324,0,514,771,1232,1041,1578,1568,878,...,467,759,2056,1302,2592,2540,3015,3281,2940,3266
Charlotte,609,835,514,0,267,723,650,1116,1074,659,...,439,484,1693,1096,2163,2180,2596,2890,2510,2904
Atlanta,867,1095,771,267,0,461,623,858,808,597,...,563,430,1474,987,1911,1958,2346,2650,2257,2677
New Orleans,1328,1556,1232,723,461,0,729,514,380,828,...,975,725,1236,1061,1551,1691,1987,2320,1887,2381
Miami,1116,1304,1041,650,623,729,0,1243,1085,1219,...,1088,1048,1959,1604,2264,2420,2697,3041,2592,3109
Dallas,1671,1897,1578,1116,858,514,1243,0,228,883,...,1202,882,739,876,1057,1179,1493,1813,1401,1868
Houston,1663,1892,1568,1074,808,380,1085,228,0,984,...,1243,942,952,1059,1180,1368,1614,1956,1512,2033
Chicago,955,1153,878,659,597,828,1219,883,984,0,...,415,177,1195,445,1778,1671,2184,2424,2122,2394
Detroit,646,835,576,522,600,976,1163,1154,1215,320,...,115,274,1515,726,2093,1990,2502,2744,2438,2712
Cleveland,541,740,467,439,563,975,1088,1202,1243,415,...,0,325,1605,836,2169,2084,2583,2834,2515,2808
Indy,844,1056,759,484,430,725,1048,882,942,177,...,325,0,1297,613,1846,1782,2263,2522,2193,2508
Denver,2140,2345,2056,1693,1474,1236,1959,739,952,1195,...,1605,1297,0,877,660,488,1011,1229,971,1214
Minneapolis,1371,1550,1302,1096,987,1061,1604,876,1059,445,...,836,613,877,0,1521,1316,1888,2082,1845,2022
Phoenix,2682,2900,2592,2163,1911,1551,2264,1057,1180,1778,...,2169,1846,660,1521,0,504,437,783,348,904
Salt Lake City,2622,2824,2540,2180,1958,1691,2420,1179,1368,1671,...,2084,1782,488,1316,504,0,644,767,658,727
LA,3104,3319,3015,2596,2346,1987,2697,1493,1614,2184,...,2583,2263,1011,1888,437,644,0,386,127,586
SF,3366,3574,3281,2890,2650,2320,3041,1813,1956,2424,...,2834,2522,1229,2082,783,767,386,0,513,263
SD,3030,3248,2940,2510,2257,1887,2592,1401,1512,2122,...,2515,2193,971,1845,348,658,127,513,0,709
Seattle,3347,3547,3266,2904,2677,2381,3109,1868,2033,2394,...,2808,2508,1214,2022,904,727,586,263,709,0